Add CapabilityStatementIndexer
DBCG/cql_engine pull request #440
Opened 2021-01-15 00:34 UTC by JPercival

* Add Indexer for CapabilityStatements
* Tests for same
* Update SearchParameterResolver to respect the index if present

2021-01-15 15:36 UTC, csandersdev requested changes
We are tracking 1.5.1-SNAPSHOT and our builds started failing today. I've marked the line of code that is causing the problem. Is it your expectation that a build on a feature branch would update the SNAPSHOTS in the repository? Seems like that should only happen on the develop branch. Not a huge deal, but FYI.

2021-01-15 15:36 UTC, csandersdev commented on engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/retrieve/RestFhirRetrieveProvider.java
> +        if (this.getIndex() == null) {
We are getting a StackOverflowError from this line. It looks like a bug to me. The code should be this.index == null not this.getIndex().

2021-01-15 16:00 UTC, msargentibm commented
Related to the SNAPSHOT being updated from a feature branch, looks like that happened back when .travis.yml was updated to use bash  scripts. Before the change, deployments were only for develop and master:  https://github.com/DBCG/cql_engine/commit/1431958c2e031f6ff9df95bde17fa373f4cf9d57#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485L25

After the change, deployments happen regardless of the branch in the bash script. Not sure if the behavior change was intentional, but wanted to point out that the behavior did used to be different.

2021-01-15 16:41 UTC, JPercival commented
It should not be publishing from feature branches. I'll fix that.

On Fri, Jan 15, 2021, 9:00 AM Matthew Sargent <notifications@github.com>
wrote:

> Related to the SNAPSHOT being updated from a feature branch, looks like
> that happened back when .travis.yml was updated to use bash scripts. Before
> the change, deployments were only for develop and master: 1431958
> #diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485L25
> <https://github.com/DBCG/cql_engine/commit/1431958c2e031f6ff9df95bde17fa373f4cf9d57#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485L25>
>
> After the change, deployments happen regardless of the branch in the bash
> script. Not sure if the behavior change was intentional, but wanted to
> point out that the behavior did used to be different.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DBCG/cql_engine/pull/440#issuecomment-761027068>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNJW7VSDQQMJFSFX4SLIQLS2BRBZANCNFSM4WDJKYSQ>
> .
>

2021-01-15 16:56 UTC, JPercival commented
I reverted the SNAPSHOT to the develop branch and disabled the build on this branch until I have time to look at it. Busy at the Connectathon today. Give you builds a shot.

2021-07-29 16:41 UTC, JPercival commented
This is going to rolled into a planning phase in the engine using a slightly different approach

2021-07-29 16:41 UTC, closed without merging